name: EdwardTran
favicon: null
layout_spectrum: 1
typography_spectrum: 0.6438216124661267
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#232229'
    - '#3b3b3b'
    - '#b49d8a'
    - '#796657'
  brandStrength: 0.25
  lightness: 0.16683596977964044
  saturation: 0.5395312381442636
  rhythmicContrast: 0.7002927523571998
purpose: []
